### ISSUE TITLE
Cannot read property 'options' of null when using multiple Select

### ISSUE THREAD

**Issue by martinscholz83** [stsrki/Blazorise#1095]
**Describe the bug**
When using multiple Select i get this error in dev console. `Cannot read property 'options' of null`. Here is how i use the Select
```html
<Select id="input_updated" class="form-control" Multiple="true" TValue="int" SelectedValues="@selectedTags">
             @if(tags.Count > 0)
              {
                         foreach(var item in tags)
                         {
                                <SelectItem Value=@item.ID>@item.Value</SelectItem>
                          }
                }
</Select>
...
...
@code {

IReadOnlyList<int> selectedTags;
}
```
`item.ID` is an `int`. I'm doing something wrong?

**Comment by stsrki** [comment]
Try setting the TValue for SelectItem also, `<SelectItem TValue="int" Value=@item.ID>@item.Value</SelectItem>`.

**Comment by stsrki** [comment]
And try this

```cs
foreach(var item in tags)
{
    var id = @item.ID;
    var value = @item.Value;
    <SelectItem TValue="int" Value="@id">@value</SelectItem>
}
```

**Comment by martinscholz83** [comment]
Neither helped. Here is the full erro from dev console
```
Microsoft.JSInterop.JSException: Cannot read property 'options' of null
TypeError: Cannot read property 'options' of null
    at Object.getSelectedOptions (https://localhost:5001/_content/Blazorise/blazorise.js:133:29)
    at https://localhost:5001/_framework/blazor.server.js:8:31421
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:8:31390)
    at https://localhost:5001/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:17165)
    at e.connection.onreceive (https://localhost:5001/_framework/blazor.server.js:1:10276)
    at WebSocket.i.onmessage (https://localhost:5001/_framework/blazor.server.js:1:38091)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at Blazorise.JSRunner.GetSelectedOptions[TValue](String elementId)
   at Blazorise.Select`1.ParseValueFromStringAsync(String value)
   at Blazorise.BaseInputComponent`1.CurrentValueHandler(String value)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
e.log @ blazor.server.js:15
```

**Comment by martinscholz83** [comment]
It happens when clicking on an item.

**Comment by martinscholz83** [comment]
Element is null
<img width="660" alt="Bildschirmfoto 2020-07-06 um 17 36 10" src="https://user-images.githubusercontent.com/19551763/86611646-3fdf4400-bfaf-11ea-9a29-05fcd81f7e66.png">

**Comment by martinscholz83** [comment]
I think i got it. When removing the id attribute from `<Select id="input_updated"` then it works as expected. It this an error in blazor?

**Comment by martinscholz83** [comment]
I see. It seems when setting the id in the src it overrides the value you calculate.
https://github.com/stsrki/Blazorise/blob/master/Source/Blazorise/Select.razor.cs#L80

**Comment by martinscholz83** [comment]
With this working i have come to another issue. For example you want to reuse the component in an modal and you want to set the selectedItems by Code. This isn't working because `selectedTags` is `IReadOnlyList<T>`. Is there a workaround to set by code?

**Comment by stsrki** [comment]
Regarding the ID, it's planned for this release in #791

Can you provide a sample code for your next problem? And please open another ticket as I will close this one since you found the solution. Is that OK? tnx
