### ISSUE TITLE
Validation issue in Blazorise 0.9.2 rc-2

### ISSUE THREAD

**Issue by robalexclark** [stsrki/Blazorise#1450]
I've got a NullReferenceException that appeared when upgrading from 0.9.2 rc-1 to rc-2 (but is also present in rc-3)

It occurs inside the Blazorise library:

```
System.NullReferenceException
  Message=Object reference not set to an instance of an object.
  Source=Blazorise
  StackTrace:
   at Blazorise.Validation.OnValidatingAll(ValidatingAllEventArgs e)
   at Blazorise.Validations.TryValidateAll()
   at Blazorise.Validations.ValidateAll()
   at CAIRS.Components.EditBoxes.DocumentEditBox.<SaveDocumentModal>d__18.MoveNext()
```

This error did not occur in rc-1. I am using bunit for tests. The test failed but I also confirmed the issue manually. My 400+ other tests pass successfully so the error is only here - I can't see what is especially different although I am using a custom validator (ValidateDocumentImportFileOk) as I am using a FileEdit to upload a document.

My edit box is defined as follows:

```
<Modal @ref="editDocumentModal" Closing="OnClosing">
    <ModalBackdrop />
    <ModalContent IsCentered="true">
        <ModalHeader>
            <ModalTitle>@title</ModalTitle>
            <CloseButton Clicked="@CloseDocumentModal" />
        </ModalHeader>
        <ModalBody>
            @if (document != null)
            {
                <Validations @ref="validations" Mode="ValidationMode.Manual" Model="@document">
                    <Validation Validator="@ValidateDocumentImportFileOk">
                        <Field>
                            <FieldLabel><strong>Document</strong></FieldLabel>
                            <FileEdit Style="opacity:1;margin-top:5px" Changed="@FileChanged" Progressed="@OnProgressed" AutoReset="false">
                                <Feedback>
                                    <ValidationError />
                                </Feedback>
                            </FileEdit>
                        </Field>
                    </Validation>
                    @if (progressPercent != null)
                    {
                        <div>
                            File upload progress: @progressPercent
                        </div>
                    }

                    <Validation>
                        <Field>
                            <FieldLabel>Description</FieldLabel>
                            <MemoEdit @bind-Text="@document.Description" MaxLength="500" Rows="3">
                                <Feedback>
                                    <ValidationError />
                                </Feedback>
                            </MemoEdit>
                        </Field>
                    </Validation>
                </Validations>
            }
        </ModalBody>
        <ModalFooter>
            <Button Color="Color.Secondary" Clicked="@CloseDocumentModal">Cancel</Button>
            @if (isSaving)
            {
                <Button Color="Color.Primary" Disabled="true">Save <Icon Name="@("fa-sync")" Class="spin-icon" /></Button>
            }
            else
            {
                <Button Color="Color.Primary" Clicked="@SaveDocumentModal">Save</Button>
            }
        </ModalFooter>
    </ModalContent>
</Modal>
```

The key bits of save and validation code behind this edit box is:
   ```
private void ValidateDocumentImportFileOk(ValidatorEventArgs e)
   {
       if (document.Data == null)
       {
           e.ErrorText = "File not selected";
           e.Status = ValidationStatus.Error;
       }
       else
       {
           e.ErrorText = null;
           e.Status = ValidationStatus.Success;
       }
   }

   private async Task SaveDocumentModal()
   {
       bool validated = validations.ValidateAll();

       if (validated)
       {
           isSaving = true;
           await CAIRSRepository.UpdateDocumentForAnimal(document);

           CloseDocumentModal(true);
           isSaving = false;
       }
   }
```

**Comment by robalexclark** [comment]
Okay, after spending a bit more time on this, it seems that the <Validation> tag is stopping the FileChanged event in the FileEdit from working at all.

```
  <Validation Validator="@ValidateDocumentImportFileOk">
                        <Field>
                            <FieldLabel><strong>Document</strong></FieldLabel>
                            <FileEdit Style="opacity:1;margin-top:5px" Changed="@FileChanged" Progressed="@OnProgressed" AutoReset="false">
                                <Feedback>
                                    <ValidationError />
                                </Feedback>
                            </FileEdit>
                        </Field>
                    </Validation>
```

At the moment the FileChanged event is not raised, but when I comment out the Validation tags the FileChanged event works ok!!

**Comment by stsrki** [comment]
Fixed
