### ISSUE TITLE
DataGrid Does Not Display

### ISSUE THREAD

**Issue by ryantgray** [stsrki/Blazorise#1479]
**Describe the bug**
I have followed the instructions at the following site and just tried implementing your Basic Example:
https://blazorise.com/docs/start/
https://blazorise.com/docs/extensions/datagrid/

When I run the application the DataGrid does not display but i get no errors in Visual Studio nor in the browser Developer Tools so i have no idea what the problem is. My project is a WebAssembly project and I'm using Chrome as my browser. I am using the following versions of the Nuget packages:

Microsoft.AspNetCore.Components.WebAssembly 3.2.1
Microsoft.AspNetCore.Components.WebAssembly.Build 3.2.1
System.Net.Http.Json 5.0.0

I was rendering just an html table on the page before so i know everything else i have set up is working correctly. Any ideas/suggestions? Thanks.

**Comment by ryantgray** [comment]
Update: I tried implementing the DataGrid again from scratch today. This time the DataGrid did display and showed my data. So i then stopped Visual Studio and didn't do anything except add the following on the DataGrid element...

Filterable="true" Sortable="true"

I then tried to run the application again and got the following error in the browser developer tools:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'blazorise' in 'window'.
      Error: Could not find 'blazorise' in 'window'.
          at https://localhost:44364/_framework/blazor.webassembly.js:1:9130
          at Array.forEach (<anonymous>)
          at p (https://localhost:44364/_framework/blazor.webassembly.js:1:9090)
          at https://localhost:44364/_framework/blazor.webassembly.js:1:9800
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44364/_framework/blazor.webassembly.js:1:9773)
          at _mono_wasm_invoke_js_marshalled (https://localhost:44364/_framework/wasm/dotnet.3.2.0.js:1:171294)
          at do_icall (<anonymous>:wasm-function[6049]:0x10f8b1)
          at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x50b6a)
          at interp_exec_method (<anonymous>:wasm-function[1120]:0x2588e)
Microsoft.JSInterop.JSException: Could not find 'blazorise' in 'window'.
Error: Could not find 'blazorise' in 'window'.
    at https://localhost:44364/_framework/blazor.webassembly.js:1:9130
    at Array.forEach (<anonymous>)
    at p (https://localhost:44364/_framework/blazor.webassembly.js:1:9090)
    at https://localhost:44364/_framework/blazor.webassembly.js:1:9800
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:44364/_framework/blazor.webassembly.js:1:9773)
    at _mono_wasm_invoke_js_marshalled (https://localhost:44364/_framework/wasm/dotnet.3.2.0.js:1:171294)
    at do_icall (<anonymous>:wasm-function[6049]:0x10f8b1)
    at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x50b6a)
    at interp_exec_method (<anonymous>:wasm-function[1120]:0x2588e)
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x33590d8 + 0x00034> in <filename unknown>:0 
  at Blazorise.TextEdit.OnFirstAfterRenderAsync () <0x32f9800 + 0x0010e> in <filename unknown>:0 
  at Blazorise.BaseComponent.OnAfterRenderAsync (System.Boolean firstRender) <0x33242f8 + 0x000ea> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x30b3788 + 0x000b6> in <filename unknown>:0

**Comment by ryantgray** [comment]
OK, apparently it's the Filterable attribute that's causing it. If i remove that attribute and just leave Sortable it works without any errors.

**Comment by stsrki** [comment]
There's no reason why Filterable would cause a problem and not work like that. Can you create a small project to reproduce the issue?

**Comment by David-Moreira** [comment]
Hello guys, 
From what has been described. 
Seems to me that the blazorise.js from the blazorise package isn't correctly loaded.
After installing blazorise did you remember to add the js resource:
  <script src="_content/Blazorise/blazorise.js"></script>
