### ISSUE TITLE
Can not bind Jobject to Datagrid

### ISSUE THREAD

**Issue by mortezabarzkar** [stsrki/Blazorise#1854]
When i was try to bind jobject to datagrid , data was shown but i got this error

Error: System.AggregateException: One or more errors occurred. ('Email' is not a member of type 'Newtonsoft.Json.Linq.JObject' (Parameter 'propertyOrFieldName'))
 ---> System.ArgumentException: 'Email' is not a member of type 'Newtonsoft.Json.Linq.JObject' (Parameter 'propertyOrFieldName')
   at System.Linq.Expressions.Expression.PropertyOrField(Expression expression, String propertyOrFieldName)
   at Blazorise.DataGrid.Utils.FunctionCompiler.GetSafeField(Expression item, String fieldName)
   at Blazorise.DataGrid.Utils.FunctionCompiler.CreateValueGetter[TItem](String fieldName)
   at Blazorise.DataGrid.DataGridColumn`1.<.ctor>b__8_2()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Blazorise.DataGrid.DataGridColumn`1.GetValue(TItem item)
   at Blazorise.DataGrid._BaseDataGridRow`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleAfterRender.OnAfterRenderAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.NotifyRenderCompletedAsync()

**Comment by stsrki** [comment]
JObject is not supported.

How do you use DataGrid with JObject in the first place? Can you show a code?

**Comment by mortezabarzkar** [comment]
that's my code

`<DataGrid TItem="JObject"
          Data="@jObjects"
          Striped="true"
          Narrow="true"
          Bordered="true"
          Hoverable="true"
          Editable="true"
          Filterable="false">
    <DataGridColumn Width="25px" TItem="JObject" Field="Email" Caption="Email">
        <DisplayTemplate>
            @context.Property("Email").Value
        </DisplayTemplate>
    </DataGridColumn>
</DataGrid>`

**Comment by stsrki** [comment]
The problem is that internally we determine the Field name and then use the reflection to build the expression tree that later is used to get and set the value from the Data object.

And here you're trying to bind to JObject, which is pretty specific and works in a completely different way than the regular object type. It's more like a dictionary.

The sooner I can commit to this is for 0.9.4 since it requires many changes internally to make it work with custom-type objects.

**Comment by mortezabarzkar** [comment]
Thank you
