### ISSUE TITLE
DataGrid with nested fields.

### ISSUE THREAD

**Issue by Merhex** [stsrki/Blazorise#1906]
Dear @stsrki,

On the DataGrid page it says it supports nested fields of a type, I tried this and it gave me the following error:

**Console error**
<details><summary>Click to expand console error block</summary>
<p>

```console
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot detect the member of FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse (Parameter 'ChassisNumber')
System.ArgumentException: Cannot detect the member of FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse (Parameter 'ChassisNumber')
   at Blazorise.DataGrid.Utils.FunctionCompiler.GetSafePropertyOrField(Expression item, String propertyOrFieldName)
   at Blazorise.DataGrid.Utils.FunctionCompiler.CreateValueGetter[LicensePlateSnapshotResponse](String fieldName)
   at Blazorise.DataGrid.DataGridColumn`1[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<.ctor>b__8_2()
   at System.Lazy`1[[System.Func`2[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[System.Func`2[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[System.Func`2[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
   at System.Lazy`1[[System.Func`2[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
   at Blazorise.DataGrid.DataGridColumn`1[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetValue(LicensePlateSnapshotResponse item)
   at Blazorise.DataGrid.DataGridColumn`1[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].FormatDisplayValue(LicensePlateSnapshotResponse item)
   at Blazorise.DataGrid._DataGridRow`1.<>c__DisplayClass0_0[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<BuildRenderTree>b__2(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Blazorise.TableRowCell.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
d.printErr @ blazor.webassembly.js:1
d.preRun.push.window.Blazor._internal.dotNetCriticalError @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.1.js:1
do_icall @ 00aba26a:0x194e58
do_icall_wrapper @ 00aba26a:0x79df9
interp_exec_method @ 00aba26a:0x44ad3
interp_runtime_invoke @ 00aba26a:0x12efff
mono_jit_runtime_invoke @ 00aba26a:0x118e5f
do_runtime_invoke @ 00aba26a:0x79d42
mono_runtime_try_invoke @ 00aba26a:0x12982
mono_runtime_invoke @ 00aba26a:0x10ec2b
mono_wasm_invoke_method @ 00aba26a:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.1.js:1
call_method @ dotnet.5.0.1.js:1
set_task_result @ dotnet.5.0.1.js:1
(anonymous) @ dotnet.5.0.1.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.1.js:1
mono_wasm_convert_return_value @ dotnet.5.0.1.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.1.js:1
do_icall @ 00aba26a:0x194de5
do_icall_wrapper @ 00aba26a:0x79df9
interp_exec_method @ 00aba26a:0x44ad3
interp_runtime_invoke @ 00aba26a:0x12efff
mono_jit_runtime_invoke @ 00aba26a:0x118e5f
do_runtime_invoke @ 00aba26a:0x79d42
mono_runtime_try_invoke @ 00aba26a:0x12982
mono_runtime_invoke @ 00aba26a:0x10ec2b
mono_wasm_invoke_method @ 00aba26a:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.1.js:1
call_method @ dotnet.5.0.1.js:1
set_task_result @ dotnet.5.0.1.js:1
(anonymous) @ dotnet.5.0.1.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.1.js:1
mono_wasm_convert_return_value @ dotnet.5.0.1.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.1.js:1
do_icall @ 00aba26a:0x194de5
do_icall_wrapper @ 00aba26a:0x79df9
interp_exec_method @ 00aba26a:0x44ad3
interp_runtime_invoke @ 00aba26a:0x12efff
mono_jit_runtime_invoke @ 00aba26a:0x118e5f
do_runtime_invoke @ 00aba26a:0x79d42
mono_runtime_try_invoke @ 00aba26a:0x12982
mono_runtime_invoke @ 00aba26a:0x10ec2b
mono_wasm_invoke_method @ 00aba26a:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.1.js:1
call_method @ dotnet.5.0.1.js:1
set_task_result @ dotnet.5.0.1.js:1
(anonymous) @ dotnet.5.0.1.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.1.js:1
mono_wasm_convert_return_value @ dotnet.5.0.1.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.1.js:1
do_icall @ 00aba26a:0x194de5
do_icall_wrapper @ 00aba26a:0x79df9
interp_exec_method @ 00aba26a:0x44ad3
interp_runtime_invoke @ 00aba26a:0x12efff
mono_jit_runtime_invoke @ 00aba26a:0x118e5f
do_runtime_invoke @ 00aba26a:0x79d42
mono_runtime_try_invoke @ 00aba26a:0x12982
mono_runtime_invoke @ 00aba26a:0x10ec2b
mono_wasm_invoke_method @ 00aba26a:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.1.js:1
call_method @ dotnet.5.0.1.js:1
set_task_result @ dotnet.5.0.1.js:1
(anonymous) @ dotnet.5.0.1.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.1.js:1
mono_wasm_convert_return_value @ dotnet.5.0.1.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.1.js:1
do_icall @ 00aba26a:0x194de5
do_icall_wrapper @ 00aba26a:0x79df9
interp_exec_method @ 00aba26a:0x44ad3
interp_runtime_invoke @ 00aba26a:0x12efff
mono_jit_runtime_invoke @ 00aba26a:0x118e5f
do_runtime_invoke @ 00aba26a:0x79d42
mono_runtime_invoke_checked @ 00aba26a:0xf65d
mono_runtime_try_invoke_array @ 00aba26a:0x10e831
ves_icall_InternalInvoke @ 00aba26a:0xed492
ves_icall_InternalInvoke_raw @ 00aba26a:0xecf57
do_icall @ 00aba26a:0x194de5
do_icall_wrapper @ 00aba26a:0x79df9
interp_exec_method @ 00aba26a:0x44ad3
interp_runtime_invoke @ 00aba26a:0x12efff
mono_jit_runtime_invoke @ 00aba26a:0x118e5f
do_runtime_invoke @ 00aba26a:0x79d42
mono_runtime_invoke_checked @ 00aba26a:0xf65d
mono_runtime_try_invoke_array @ 00aba26a:0x10e831
ves_icall_InternalInvoke @ 00aba26a:0xed492
ves_icall_InternalInvoke_raw @ 00aba26a:0xecf57
do_icall @ 00aba26a:0x194de5
do_icall_wrapper @ 00aba26a:0x79df9
interp_exec_method @ 00aba26a:0x44ad3
interp_runtime_invoke @ 00aba26a:0x12efff
mono_jit_runtime_invoke @ 00aba26a:0x118e5f
do_runtime_invoke @ 00aba26a:0x79d42
mono_runtime_try_invoke @ 00aba26a:0x12982
mono_runtime_invoke @ 00aba26a:0x10ec2b
mono_wasm_invoke_method @ 00aba26a:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.1.js:1
call_method @ dotnet.5.0.1.js:1
(anonymous) @ dotnet.5.0.1.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
h @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
invokeWhenHeapUnlocked @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
t.dispatchEvent @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
e.onGlobalEvent @ blazor.webassembly.js:1
Show 45 more frames
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot detect the member of FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse (Parameter 'Brand')
System.ArgumentException: Cannot detect the member of FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse (Parameter 'Brand')
   at Blazorise.DataGrid.Utils.FunctionCompiler.GetSafePropertyOrField(Expression item, String propertyOrFieldName)
   at Blazorise.DataGrid.Utils.FunctionCompiler.CreateValueGetter[LicensePlateSnapshotResponse](String fieldName)
   at Blazorise.DataGrid.DataGridColumn`1[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<.ctor>b__8_2()
   at System.Lazy`1[[System.Func`2[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[System.Func`2[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[System.Func`2[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
   at System.Lazy`1[[System.Func`2[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
   at Blazorise.DataGrid.DataGridColumn`1[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetValue(LicensePlateSnapshotResponse item)
   at Blazorise.DataGrid.DataGridColumn`1[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].FormatDisplayValue(LicensePlateSnapshotResponse item)
   at Blazorise.DataGrid._DataGridRow`1.<>c__DisplayClass0_0[[FleetManagement.Blazor.Responses.LicensePlateSnapshotResponse, FleetManagement.Blazor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<BuildRenderTree>b__2(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Blazorise.TableRowCell.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
d.printErr @ blazor.webassembly.js:1
d.preRun.push.window.Blazor._internal.dotNetCriticalError @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.1.js:1
do_icall @ 00aba26a:0x194e58
do_icall_wrapper @ 00aba26a:0x79df9
interp_exec_method @ 00aba26a:0x44ad3
interp_runtime_invoke @ 00aba26a:0x12efff
mono_jit_runtime_invoke @ 00aba26a:0x118e5f
do_runtime_invoke @ 00aba26a:0x79d42
mono_runtime_invoke_checked @ 00aba26a:0xf65d
mono_runtime_try_invoke_array @ 00aba26a:0x10e831
ves_icall_InternalInvoke @ 00aba26a:0xed492
ves_icall_InternalInvoke_raw @ 00aba26a:0xecf57
do_icall @ 00aba26a:0x194de5
do_icall_wrapper @ 00aba26a:0x79df9
interp_exec_method @ 00aba26a:0x44ad3
interp_runtime_invoke @ 00aba26a:0x12efff
mono_jit_runtime_invoke @ 00aba26a:0x118e5f
do_runtime_invoke @ 00aba26a:0x79d42
mono_runtime_try_invoke @ 00aba26a:0x12982
mono_runtime_invoke @ 00aba26a:0x10ec2b
mono_wasm_invoke_method @ 00aba26a:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.1.js:1
call_method @ dotnet.5.0.1.js:1
(anonymous) @ dotnet.5.0.1.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
h @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
onBreakpoint @ blazorise.js:600
(anonymous) @ blazorise.js:634
````
</p>
</details>
</summary>

Here is the razor component containing the grid:

**LicensePlateHistory.razor**
```HTML+Razor
@page "/licensePlates/history/{identifier}"
@using Blazor.Responses

<Heading Size="HeadingSize.Is3">Details for license plate: @Identifier</Heading>

<Divider />

<Heading Size="HeadingSize.Is4">History</Heading>

<DataGrid TItem="LicensePlateSnapshotResponse"
          Data="@History"
          ReadData="@ReadData"
          TotalItems="@TotalItems"
          PageSize="@PageSize"
          CurrentPage="@Page"
          ShowPager="true">
    <ChildContent>
        <DataGridColumn TItem="LicensePlateSnapshotResponse" Field="@nameof(LicensePlateSnapshotResponse.MotorVehicle.ChassisNumber)" Caption="VIN"></DataGridColumn>
        <DataGridColumn TItem="LicensePlateSnapshotResponse" Field="@nameof(LicensePlateSnapshotResponse.MotorVehicle.Brand)" Caption="Brand"></DataGridColumn>
        <DataGridColumn TItem="LicensePlateSnapshotResponse" Field="@nameof(LicensePlateSnapshotResponse.MotorVehicle.Model)" Caption="Model"></DataGridColumn>
        <DataGridCheckColumn TItem="LicensePlateSnapshotResponse" Field="@nameof(LicensePlateSnapshotResponse.InUse)" Caption="Activated">
            <DisplayTemplate>
                <Check TValue="bool" Checked="context.InUse" Disabled="true" ReadOnly="true" />
            </DisplayTemplate>
        </DataGridCheckColumn>
    </ChildContent>
    <EmptyTemplate>
        <Paragraph>No items to be displayed.</Paragraph>
    </EmptyTemplate>
    <LoadingTemplate>
        <Loader />
    </LoadingTemplate>
</DataGrid>
```

These are the classes used

**LicensePlateSnapshotRespone**
```C#
using System;

namespace FleetManagement.Blazor.Responses
{
    public class LicensePlateSnapshotResponse
    {
        public bool InUse { get; set; }
        public DateTime SnapshotDate { get; set; }
        public MotorVehicleSimpleResponse MotorVehicle { get; set; }
    }
}
```

**MotorVehicleSimpleResponse**
```C#
namespace FleetManagement.Blazor.Responses
{
    public class MotorVehicleSimpleResponse
    {
        public string ChassisNumber { get; set; }
        public string Model { get; set; }
        public string Brand { get; set; }
    }
}
```

**Comment by stsrki** [comment]
For nested fields, you don't use `nameof`. You need to define the path explicitly. 

```cshtml
<DataGridColumn TItem="LicensePlateSnapshotResponse" Field="MotorVehicle.ChassisNumber" Caption="VIN"></DataGridColumn>
```

**Comment by mahmudkhalifa** [comment]
I did remove the NameOf then it shows an error

![image](https://user-images.githubusercontent.com/62502565/160292217-e22a8e61-ded9-437d-9880-f826fe0c0803.png)

**Comment by ssinghm32** [comment]
@stsrki  Any chance the documentation can be updated to mention that nameof() is not required for Nested Fields. 
https://blazorise.com/docs/extensions/datagrid/getting-started

It was not clear going through the documentation and could have saved me many hours until I decided to check for Issues in Github :)

Thanks

**Comment by bkea** [comment]
@stsrki  I am having the same issue with complex types in a data grid.  I followed your instructions but my subclass properties do not appear (the headings are there). I do not see an error in the browsers developer window.


```
@page "/Loadinglist"
@using TESTBlazor1.Data

<h3>Loading List</h3>
<DataGrid TItem="LoadData"
          Data="@loadList">
    <DataGridColumns>
        <DataGridColumn Field="@nameof(LoadData.loadId)" Caption="#" />
        <DataGridColumn Field="@nameof(LoadData.caliber)" Caption="Caliber" />
        <DataGridColumn TItem="LoadData" Field="powder.powderName" Caption="Powder" />
        <DataGridColumn TItem="LoadData" Field="bullet.bulletName" Caption="Bullet" />
        <DataGridColumn TItem="LoadData" Field="bullet.bulletWT" Caption="Bullet WT" />
        <DataGridColumn Field="@nameof(LoadData.chargeWT)" Caption="Charge" />
    </DataGridColumns>
</DataGrid>
```

```
@code {
    [Inject]
    public GetLoadData getLoadData { get; set; }
    private List<LoadData>? loadList;

    protected override async Task OnInitializedAsync()
    {
        loadList = await getLoadData.GetDataAsync();
        await base.OnInitializedAsync();
    }
}
```


```
namespace TESTBlazor1.Data
{
    public class LoadData
    {
        public int loadId { get; set; } = new int();
        public string caliber { get; set; } =  string.Empty;
        public PowderInfo powder { get; set; } = new PowderInfo();
        public BulletInfo bullet { get; set; } = new BulletInfo();
        public decimal chargeWT { get; set; } = new decimal();
        public string comments { get; set; } = string.Empty;
    }
}
```

```
namespace TESTBlazor1.Data
{
    public class BulletInfo
    {
        public int bulletID { get; set; } = new int();
        public string bulletManufacture { get; set; } = string.Empty;
        public string bulletName { get; set; } = string.Empty;
        public decimal bulletWT { get; set; } = decimal.Zero;
        public int bulletProductId { get; set; } = new int();

    }
}
```

```
namespace TESTBlazor1.Data
{
    public class PowderInfo
    {
        public int powderID { get; set; } = new int();
        public string powderManufacture { get; set; } = string.Empty;
        public string powderName { get; set; } = string.Empty;
    }
}
```

```
[
  {
    "loadId": 1,
    "caliber": "22-250",
    "PowderInfo": {
      "powderID": 1,
      "powderManufacture": "Hodgdons",
      "powderName": "H4350"
    },
    "BulletInfo": {
      "bulletID": 1,
      "bulletManufacture": "Nosler",
      "bulletName": "Ballistic Tip",
      "bulletWT": 55,
      "bulletProductId": "1122"

    },
    "chargeWT": 38.0,
    "comments": "my other comments"
  },
  {
    "loadId": 2,
    "caliber": "30-06",
    "PowderInfo": {
      "powderID": "9",
      "powderManufacture": "Allient",
      "powderName": "Reloader 17"
    },
    "BulletInfo": {
      "bulletID": 2,
      "bulletManufacture": "Sierra",
      "bulletName": "Game King",
      "bulletWT": 150,
      "bulletProductId": "1133"
    },
    "chargeWT": 57.5,
    "comments": "my comments"
  }
]
```

**Comment by AllenConway** [comment]
> For nested fields, you don't use `nameof`. You need to define the path explicitly.
> 
> ```
> <DataGridColumn TItem="LicensePlateSnapshotResponse" Field="MotorVehicle.ChassisNumber" Caption="VIN"></DataGridColumn>
> ```

Also note that not only is `@nameof` not required, but the literal path will also omit the type used. Therefore to show the exact code instead of this:

`<DataGridColumn TItem="LicensePlateSnapshotResponse" Field="@nameof(LicensePlateSnapshotResponse.MotorVehicle.ChassisNumber)" Caption="VIN"></DataGridColumn>`

It is now this, in the correct form:
`<DataGridColumn TItem="LicensePlateSnapshotResponse" Field="MotorVehicle.ChassisNumber" Caption="VIN"></DataGridColumn>`
