### ISSUE TITLE
Error on working project After upgrade to 0.9.3

### ISSUE THREAD

**Issue by mortezabarzkar** [stsrki/Blazorise#1979]
Hi
i have some error after upgrading working project to 0.9.3

 Error: Microsoft.JSInterop.JSException: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.setSelectedOptions (https://localhost:44384/_content/Blazorise/blazorise.js:157:37)
    at https://localhost:44384/_framework/blazor.server.js:1:70043
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44384/_framework/blazor.server.js:1:70009)
    at https://localhost:44384/_framework/blazor.server.js:1:26293
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44384/_framework/blazor.server.js:1:26263)
    at e.processIncomingData (https://localhost:44384/_framework/blazor.server.js:1:24201)
    at e.connection.onreceive (https://localhost:44384/_framework/blazor.server.js:1:17286)
    at WebSocket.i.onmessage (https://localhost:44384/_framework/blazor.server.js:1:46503)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Blazorise.Select`1.<>c__DisplayClass3_0.<<SetParametersAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Blazorise.Base.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by mortezabarzkar** [comment]
My Code

`
<Select TValue="int" Multiple="true" SelectedValues="@selectedCampaigns" SelectedValuesChanged="@OnSelectedCampaignChanged" MaxVisibleItems="5">
                        @* required item.ID null control *@
                        @foreach (var item in campaigns)
                        {
                            <SelectItem Value="@(item.ID ?? 0)">@(item.TitleTexts?.FirstOrDefault(x => x.LanguageID == State.User.DefaultLanguage)?.Text)</SelectItem>
                        }
                    </Select>
`

**Comment by mortezabarzkar** [comment]
@stsrki

**Comment by stsrki** [comment]
This usually happens after the update because the browser caches the JS files. Try refresh with ctrl+F5.

**Comment by stsrki** [comment]
PS. I added some new functions for Select Multiple modes and that is why it's not working. As stated, just clear the cache.

**Comment by mortezabarzkar** [comment]
After cleaning still i have error

**Comment by stsrki** [comment]
Hmm, could it be that `selectedCampaigns` is null?

**Comment by mortezabarzkar** [comment]
not null but empty
 private List<int> selectedCampaigns = new List<int>();

**Comment by stsrki** [comment]
Can you go into dev tools, open `content/Blazorise/blazorise.js`, and put the breakpoint on `setSelectedOptions`. See what happens.

**Comment by mortezabarzkar** [comment]
in this line
   const len = element.options.length;

options is undefined

```
 setSelectedOptions: (elementId, values) => {
        const element = document.getElementById(elementId);
        const len = element.options.length;

        for (var i = 0; i < len; i++) {
            const opt = element.options[i];

            if (values && values.find(x => x?.toString() === opt.value)) {
                opt.selected = true;
            } else {
                opt.selected = false;
            }
        }
    },
```

**Comment by stsrki** [comment]
That is a bug definitely. OK I will fix it for the next patch.

**Comment by mortezabarzkar** [comment]
Thank you

**Comment by mortezabarzkar** [comment]
after upgrading 9.3.1 still have error
@stsrki

![4](https://user-images.githubusercontent.com/6237492/111458336-5d61d180-872a-11eb-9565-b8d8a96a4391.PNG)

**Comment by stsrki** [comment]
Please clear the cache with Ctrl+F5. It should be fixed.

**Comment by mortezabarzkar** [comment]
it's ok thank you
