### ISSUE TITLE
093:  TextEdit initialize js :: the element parameter is null :: Release Mode not Local Debug Mode

### ISSUE THREAD

**Issue by sks-ttaylor** [stsrki/Blazorise#1984]
Upgraded to 093 release, 
Visual Studio 2019 latest,
Works fine in local debug mode.
Does not work when::
Publish to IIS, compiled with Release mode
Chrome Browser latest, debug window reports "Element" parameter is null

**Comment by stsrki** [comment]
Did you cleared browser cache?

**Comment by sks-ttaylor** [comment]
Yes,  clear all cache,  used different browsers,

**Comment by stsrki** [comment]
Recheck what are your publish settings. And do you have wwwroot. 

I also host demo apps in IIS without any problems.

**Comment by sks-ttaylor** [comment]
yes, i have wwwroot and expected subfolders _content, _framework, etc.
i do not think it is a publish issue.
I'm reverting back to 093-rc3 and testing again...

**Comment by sks-ttaylor** [comment]
093-rc3 did not work, however 093-preview6 did...

**Comment by stsrki** [comment]
Preview 6 is an old version. Who can remember what changed back then 😅

**Comment by sks-ttaylor** [comment]
going to try 093-rc1, then 093-rc2...

**Comment by sks-ttaylor** [comment]
093-rc1 worked

**Comment by sks-ttaylor** [comment]
093-rc2 did not work

**Comment by stsrki** [comment]
Can you show stacktrace?

**Comment by sks-ttaylor** [comment]
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Event 3 is already tracked
      Error: Event 3 is already tracked
          at e.add (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:42456)
          at e.setListener (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:40690)
          at e.applyAttribute (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:36857)
          at e.insertElement (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:35691)
          at e.insertFrame (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:34562)
          at e.applyEdits (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:32948)
          at e.updateComponent (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:32264)
          at Object.t.renderBatch (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:12129)
          at Object.window.Blazor._internal.renderBatch (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:61899)
          at Object.w [as invokeJSFromDotNet] (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:64421)
Microsoft.JSInterop.JSException: Event 3 is already tracked
Error: Event 3 is already tracked
    at e.add (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:42456)
    at e.setListener (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:40690)
    at e.applyAttribute (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:36857)
    at e.insertElement (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:35691)
    at e.insertFrame (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:34562)
    at e.applyEdits (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:32948)
    at e.updateComponent (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:32264)
    at Object.t.renderBatch (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:12129)
    at Object.window.Blazor._internal.renderBatch (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:61899)
    at Object.w [as invokeJSFromDotNet] (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:64421)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
d.printErr @ blazor.webassembly.js:1
d.preRun.push.window.Blazor._internal.dotNetCriticalError @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.3.js:1
do_icall @ 00aba242:0x194e4e
do_icall_wrapper @ 00aba242:0x79df9
interp_exec_method @ 00aba242:0x44ad3
interp_runtime_invoke @ 00aba242:0x12efff
mono_jit_runtime_invoke @ 00aba242:0x118e5f
do_runtime_invoke @ 00aba242:0x79d42
mono_runtime_invoke_checked @ 00aba242:0xf65d
mono_runtime_try_invoke_array @ 00aba242:0x10e831
ves_icall_InternalInvoke @ 00aba242:0xed492
ves_icall_InternalInvoke_raw @ 00aba242:0xecf57
do_icall @ 00aba242:0x194ddb
do_icall_wrapper @ 00aba242:0x79df9
interp_exec_method @ 00aba242:0x44ad3
interp_runtime_invoke @ 00aba242:0x12efff
mono_jit_runtime_invoke @ 00aba242:0x118e5f
do_runtime_invoke @ 00aba242:0x79d42
mono_runtime_try_invoke @ 00aba242:0x12982
mono_runtime_invoke @ 00aba242:0x10ec2b
mono_wasm_invoke_method @ 00aba242:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.3.js:1
call_method @ dotnet.5.0.3.js:1
(anonymous) @ dotnet.5.0.3.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
h @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
invokeWhenHeapUnlocked @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
t.dispatchEvent @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
e.onGlobalEvent @ blazor.webassembly.js:1
focus @ blazorise.js:226
(anonymous) @ blazor.webassembly.js:1
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.3.js:1
do_icall @ 00aba242:0x194e4e
do_icall_wrapper @ 00aba242:0x79df9
interp_exec_method @ 00aba242:0x44ad3
interp_runtime_invoke @ 00aba242:0x12efff
mono_jit_runtime_invoke @ 00aba242:0x118e5f
do_runtime_invoke @ 00aba242:0x79d42
mono_runtime_try_invoke @ 00aba242:0x12982
mono_runtime_invoke @ 00aba242:0x10ec2b
mono_wasm_invoke_method @ 00aba242:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.3.js:1
call_method @ dotnet.5.0.3.js:1
(anonymous) @ dotnet.5.0.3.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.3.js:1
do_icall @ 00aba242:0x194e4e
do_icall_wrapper @ 00aba242:0x79df9
interp_exec_method @ 00aba242:0x44ad3
interp_runtime_invoke @ 00aba242:0x12efff
mono_jit_runtime_invoke @ 00aba242:0x118e5f
do_runtime_invoke @ 00aba242:0x79d42
mono_runtime_try_invoke @ 00aba242:0x12982
mono_runtime_invoke @ 00aba242:0x10ec2b
mono_wasm_invoke_method @ 00aba242:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.3.js:1
call_method @ dotnet.5.0.3.js:1
set_task_result @ dotnet.5.0.3.js:1
(anonymous) @ dotnet.5.0.3.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.3.js:1
d.preRun.push.window.Blazor._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.3.js:1
do_icall @ 00aba242:0x194e4e
do_icall_wrapper @ 00aba242:0x79df9
interp_exec_method @ 00aba242:0x44ad3
interp_runtime_invoke @ 00aba242:0x12efff
mono_jit_runtime_invoke @ 00aba242:0x118e5f
do_runtime_invoke @ 00aba242:0x79d42
mono_runtime_try_invoke @ 00aba242:0x12982
mono_runtime_invoke @ 00aba242:0x10ec2b
mono_wasm_invoke_method @ 00aba242:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.3.js:1
call_method @ dotnet.5.0.3.js:1
(anonymous) @ dotnet.5.0.3.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.3.js:1
do_icall @ 00aba242:0x194e4e
do_icall_wrapper @ 00aba242:0x79df9
interp_exec_method @ 00aba242:0x44ad3
interp_runtime_invoke @ 00aba242:0x12efff
mono_jit_runtime_invoke @ 00aba242:0x118e5f
do_runtime_invoke @ 00aba242:0x79d42
mono_runtime_try_invoke @ 00aba242:0x12982
mono_runtime_invoke @ 00aba242:0x10ec2b
mono_wasm_invoke_method @ 00aba242:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.3.js:1
call_method @ dotnet.5.0.3.js:1
(anonymous) @ dotnet.5.0.3.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.3.js:1
do_icall @ 00aba242:0x194e4e
do_icall_wrapper @ 00aba242:0x79df9
interp_exec_method @ 00aba242:0x44ad3
interp_runtime_invoke @ 00aba242:0x12efff
mono_jit_runtime_invoke @ 00aba242:0x118e5f
do_runtime_invoke @ 00aba242:0x79d42
mono_runtime_try_invoke @ 00aba242:0x12982
mono_runtime_invoke @ 00aba242:0x10ec2b
mono_wasm_invoke_method @ 00aba242:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.3.js:1
call_method @ dotnet.5.0.3.js:1
set_task_result @ dotnet.5.0.3.js:1
(anonymous) @ dotnet.5.0.3.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.3.js:1
d.preRun.push.window.Blazor._internal.getLazyAssemblies @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.3.js:1
do_icall @ 00aba242:0x194e4e
do_icall_wrapper @ 00aba242:0x79df9
interp_exec_method @ 00aba242:0x44ad3
interp_runtime_invoke @ 00aba242:0x12efff
mono_jit_runtime_invoke @ 00aba242:0x118e5f
do_runtime_invoke @ 00aba242:0x79d42
mono_runtime_invoke_checked @ 00aba242:0xf65d
mono_runtime_try_invoke_array @ 00aba242:0x10e831
ves_icall_InternalInvoke @ 00aba242:0xed492
ves_icall_InternalInvoke_raw @ 00aba242:0xecf57
do_icall @ 00aba242:0x194ddb
do_icall_wrapper @ 00aba242:0x79df9
interp_exec_method @ 00aba242:0x44ad3
interp_runtime_invoke @ 00aba242:0x12efff
mono_jit_runtime_invoke @ 00aba242:0x118e5f
do_runtime_invoke @ 00aba242:0x79d42
mono_runtime_try_invoke @ 00aba242:0x12982
mono_runtime_invoke @ 00aba242:0x10ec2b
mono_wasm_invoke_method @ 00aba242:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.3.js:1
call_method @ dotnet.5.0.3.js:1
(anonymous) @ dotnet.5.0.3.js:1
callEntryPoint @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
a @ blazor.webassembly.js:1
Promise.then (async)
u @ blazor.webassembly.js:1
a @ blazor.webassembly.js:1
Promise.then (async)
u @ blazor.webassembly.js:1
a @ blazor.webassembly.js:1
Promise.then (async)
u @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
g @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
n @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Show 25 more frames
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read property 'addEventListener' of null
      TypeError: Cannot read property 'addEventListener' of null
          at Object.initialize (https://dev.{redacted}.com/_content/Blazorise/blazorise.js:258:21)
          at https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:3942
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:3908)
          at Object.w [as invokeJSFromDotNet] (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:64218)
          at _mono_wasm_invoke_js_blazor (https://dev.{redacted}.com/_framework/dotnet.5.0.3.js:1:190800)
          at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
          at do_icall_wrapper (<anonymous>:wasm-function[3305]:0x79df9)
          at interp_exec_method (<anonymous>:wasm-function[2155]:0x44ad3)
          at interp_runtime_invoke (<anonymous>:wasm-function[7862]:0x12efff)
Microsoft.JSInterop.JSException: Cannot read property 'addEventListener' of null
TypeError: Cannot read property 'addEventListener' of null
    at Object.initialize (https://dev.{redacted}.com/_content/Blazorise/blazorise.js:258:21)
    at https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:3942
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:3908)
    at Object.w [as invokeJSFromDotNet] (https://dev.{redacted}.com/_framework/blazor.webassembly.js:1:64218)
    at _mono_wasm_invoke_js_blazor (https://dev.{redacted}.com/_framework/dotnet.5.0.3.js:1:190800)
    at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
    at do_icall_wrapper (<anonymous>:wasm-function[3305]:0x79df9)
    at interp_exec_method (<anonymous>:wasm-function[2155]:0x44ad3)
    at interp_runtime_invoke (<anonymous>:wasm-function[7862]:0x12efff)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[System.Boolean, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Blazorise.TextEdit.OnFirstAfterRenderAsync()
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by sks-ttaylor** [comment]
if you want, i can email the dev site url to you...

**Comment by stsrki** [comment]
It will not hurt :)

Also, send me one usage example of TextEdit where you think it might break. It seems that could be a problem.

**Comment by sks-ttaylor** [comment]
emailing to st.srki@gmail.com

**Comment by sks-ttaylor** [comment]
send... what is deployed to the dev site is 093-rc2

**Comment by sks-ttaylor** [comment]
Found the issue ::  Changed code to use AutoFocus instead...
Thank you...

protected override void OnAfterRender(bool firstRender)
  {
    base.OnAfterRender(firstRender); 
    if (firstRender)
    {
      RefUsername.Focus(true);
    }

  }
