### ISSUE TITLE
Uncaught json exception when IndexableOption<object> is empty anonymous object

### ISSUE THREAD

**Issue by czf** [stsrki/Blazorise#2123]
**Describe the bug**
when setting HoverBackgroundColor to an empty anonymous object on BarChartDataset and triggering the onclick handler for chart it was used for I ran into an unhelpful exception that took a while to track down:
```
System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.backgroundColor | LineNumber: 0 | BytePositionInLine: 20.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.Converters.StringConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfo`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Blazorise.Charts.BarChartModel, Blazorise.Charts, Version=0.9.3.3, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, BarChartModel& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Blazorise.Charts.BarChartModel, Blazorise.Charts, Version=0.9.3.3, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, BarChartModel& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Blazorise.Charts.BarChartModel, Blazorise.Charts, Version=0.9.3.3, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
```
   

**To Reproduce**

1. create a bar chart
2. add an onclick handler for the chart
3. set `HoverBackgroundColor = new IndexableOption<object>(new { })` for the barchartdataset
4. run the chart and click on the bars.  You'll see the error in the browser console and it will prevent the onclick handler from firing

**Expected behavior**
Should there be more validation for the properties that use IndexableOption<object>?

**Comment by stsrki** [comment]
Why do you use empty IndexableOption? It is doing what it is supposed to do. It tries to parse a value but you're giving it an empty anonymous object which is basically invalid. It has no fields whatsoever.

**Comment by czf** [comment]
It was a mistake that I had trouble tracking down.  Just wanted to call it out in case someone else ran into it.

**Comment by stsrki** [comment]
Sure, no problem. BTW IndexableOption has an implicit operators so you can define it as `HoverBackgroundColor = "#ff00cc";`, for example.

**Comment by czf** [comment]
is there another use case where the properties aren't using string?  could this be `IndexableOption<string>`?

**Comment by stsrki** [comment]
Yes, you can also use a list or an array, eg. `BorderColor = new List<string>() { "1", "2" },`.

IndexableOption is used for scenarios where you need to pass either a single value or a list of values. That is how chartjs works and we needed to support it.
