### ISSUE TITLE
modal @ref error

### ISSUE THREAD

**Issue by PashaGoroshko** [stsrki/Blazorise#217]
Hey!

https://blazorise.com/docs/components/modal/

```
<Modal @ref="modalRef">
</Modal>
```
Unable to declare local variable **modalRef**
```
    // reference to the modal component
    private Modal modalRef;
```

Errors:
Error CS0229 The ambiguity between "__generated__MyPage.modalRef" and "__generated__MyPage.modalRef"
Error CS0102 Type "__generated__MyPage" already contains a definition for "modalRef".

![image](https://user-images.githubusercontent.com/16119359/63509882-ea5c8e80-c4e5-11e9-8738-78b3e2b55018.png)

**Comment by PashaGoroshko** [comment]
@stsrki 
the error is gone, but now another appeared

Microsoft.JSInterop.JSException: Could not find 'blazorise' in 'window'.
Error: Could not find 'blazorise' in 'window'.
    at https://localhost:44321/_framework/blazor.server.js:8:27768
    at Array.forEach (<anonymous>)
    at d (https://localhost:44321/_framework/blazor.server.js:8:27729)
    at https://localhost:44321/_framework/blazor.server.js:8:28342
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44321/_framework/blazor.server.js:8:28316)
    at https://localhost:44321/_framework/blazor.server.js:1:19148
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44321/_framework/blazor.server.js:1:19119)
    at e.processIncomingData (https://localhost:44321/_framework/blazor.server.js:1:17165)
   at Microsoft.JSInterop.JSRuntimeBase.InvokeWithDefaultCancellation[T](String identifier, IEnumerable`1 args)
   at Blazorise.BaseTextEdit.OnFirstAfterRenderAsync()
   at Blazorise.BaseComponent.OnAfterRenderAsync()
   at Microsoft.AspNetCore.Components.Rendering.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by stsrki** [comment]
It seems like the same error as #216 

You should add missing js files manually if you're using server-side Blazor.

https://github.com/stsrki/Blazorise#server-side

**Comment by PashaGoroshko** [comment]
@stsrki  thx
