### ISSUE TITLE
Datagrid Resize causes exception with javascript

### ISSUE THREAD

**Issue by sanguinal** [stsrki/Blazorise#2314]
**Describe the bug**
Error caused at runtime using resize header
**To Reproduce**
1. Create a datagrid with                      Resizable="true"
                      ResizeMode="@DataGridResizeMode.Header"
2. run the program
blazor.server.js:21 [2021-05-07T15:51:29.989Z] Error: Microsoft.JSInterop.JSException: Could not find 'blazoriseDataGrid.destroyResizable' ('blazoriseDataGrid' was undefined).
Error: Could not find 'blazoriseDataGrid.destroyResizable' ('blazoriseDataGrid' was undefined).
    at https://localhost:44387/_framework/blazor.server.js:1:67390
    at Array.forEach (<anonymous>)
    at e.findFunction (https://localhost:44387/_framework/blazor.server.js:1:67350)
    at v (https://localhost:44387/_framework/blazor.server.js:1:69092)
    at https://localhost:44387/_framework/blazor.server.js:1:70038
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44387/_framework/blazor.server.js:1:70011)
    at https://localhost:44387/_framework/blazor.server.js:1:26293
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44387/_framework/blazor.server.js:1:26263)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Blazorise.DataGrid.DataGrid`1.RecalculateResize()
   at Blazorise.DataGrid.DataGrid`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
**Expected behavior**
A resizable datagrid

It maybe that I have used this feature incorrectly.

**Comment by stsrki** [comment]
Do you have

`<script src="_content/Blazorise.DataGrid/blazorise.datagrid.js"></script>`

defined in index,html or _Host.cshtml file ?

**Comment by sanguinal** [comment]
Ah it is "_content/Blazorise.DataGrid/blazorise.datagrid.css" - Playing with it now. I think some of my other css is stopping it resizing.

**Comment by stsrki** [comment]
Cool, glad I could help :)
