### ISSUE TITLE
Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Blazorise.IJSRunner'

### ISSUE THREAD

**Issue by aford22** [stsrki/Blazorise#58]
Blazorise Material 0.6.2-preview1-19154-02
.net core 3 preview 3

Add a SimpleButton to a Razor Components page, start in debug mode and navigate to the page. Chrome console error:

`Uncaught (in promise) Error: System.InvalidOperationException: Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Blazorise.IJSRunner'.
   at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously(String assemblyName, String methodIdentifier, Object targetInstance, String argsJson)
   at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
    at endInvokeDotNetFromJS (components.server.js:23)
    at components.server.js:23
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (components.server.js:23)
    at components.server.js:16
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (components.server.js:16)
    at e.processIncomingData (components.server.js:16)
    at e.connection.onreceive (components.server.js:16)
    at WebSocket.i.onmessage (components.server.js:16)`

Page will not render. I not managed to get Blazorise working with Razor Components.

**Comment by stsrki** [comment]
I have just tried to create Razor Components project and I cannot see any problem.

Did you go through all of the steps when setting up the project with Blazorise? Do you have the [registration](https://github.com/stsrki/Blazorise#registrations) methods in your Startup.cs?

Also, can you tell me what provider are you using? Bootstrap, Bulma or Material?

**Comment by aford22** [comment]
Hi there. I believe you have already fixed the problem in Blazorise.Bootstrap.Config.cs:
`serviceCollection.AddScoped<IJSRunner, BootstrapJSRunner>();`

but not in Blazorise.Material.Config.cs:
`serviceCollection.AddSingleton<IJSRunner, MaterialJSRunner>();`

**Comment by stsrki** [comment]
You're right. I forgot to fix material and also bulma implementation. Will be fixed in the 0.6.3 :)
