### ISSUE TITLE
Unable to Use Charts Extension with Server Render Mode

### ISSUE THREAD

**Issue by brandon-james105** [stsrki/Blazorise#992]
**Describe the bug**
When a project is set to server rendering mode, the Charts extension will not respond to a call to Update(). Call stack: 

```
System.ArgumentNullException: Value cannot be null. (Parameter 'jsRuntime')
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeAsync[TValue](IJSRuntime jsRuntime, String identifier, Object[] args)
   at Blazorise.Charts.JS.Update(IJSRuntime runtime, String canvasId)
   at Blazorise.Charts.BaseChart`4.Update()
   at Project.Pages.PlayerProfile.HandleRedraw() in C:\Users\Brandon James\source\repos\Project\Project\Pages\PlayerProfile.razor.cs:line 125
   at Project.Pages.PlayerProfile.OnInitializedAsync() in C:\Users\Brandon James\source\repos\Project\Project\Pages\PlayerProfile.razor.cs:line 116
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**To Reproduce**
```
async Task HandleRedraw()
{
        await TotalScoreHistoryChart.Clear();

        await TotalScoreHistoryChart.AddDataSet(GetLineChartDataset(HighScoreType.Total));

        await TotalScoreHistoryChart.Update(); // <-- Problem line
}
```

**Expected behavior**
When calling the chart update method, the chart should show the data I have included.

**Comment by stsrki** [comment]
Hi @brandon-james105 , this is already fixed in #881 and will be released soon with v0.9.1
